### PR TITLE
Do not allow roles below editor

### LINKED ISSUE #91: Do not allow roles below editor
The plugin should not proceed if it does not receive at least an editor role for the token,. If it does, then someone fixes it by upgrading the author account to an editor, it will then appear to work, but the plugin will not go create the wordpress resource group with corresponding callback URL, leading to a bunch of orphaned resources.

### LINKED ISSUE #120: _transient_coyote_api_error_count isn't cleared when succesfully creating a profile
When testing the plugin settings with incomplete or incorrect credentials the _transient_coyote_api_error_count increments in the database. When a valid profile is linked I assume the transient should be cleared?

### PR DESCRIPTION
**Pull request by robbinrietdijk**

### CODE REVIEW

File: php/PluginConfiguration.php [hunk 1]
```diff
@@ -10,6 +12,7 @@ class PluginConfiguration
     public const METUM = 'Alt';
     public const DEFAULT_ENDPOINT = 'https://staging.coyote.pics';
     public const RESOURCE_GROUP_NAME = 'WordPress';
+    public const ALLOWED_ROLES = ['editor','admin','owner'];
```
Comment (jkva) [inline php/PluginConfiguration.php]: Inconsistent comma spacing

**Review by jkva — CHANGES_REQUESTED** [review]
Looks good! Just a nitpick, but love the added abstraction here and there.

File: php/PluginConfiguration.php (hunk 1 above)
Comment (robbinrietdijk) [reply php/PluginConfiguration.php]: Done
